version: '3.8'

services:
  nuxt3:
    container_name: nuxt3
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    network_mode: "Library"